"""baseline schema

Full current schema (models/models.py), equivalent to src/ev_station_db.sql
plus src/migrations/0001-0004. Those raw .sql files predate Alembic and are
kept only as a historical record for databases provisioned before this
revision existed - a DB that already has them applied should be `alembic
stamp`-ed at this revision rather than having it re-run. See src/alembic/README (or the repo's deploy docs) for the stamp-vs-upgrade decision.

Revision ID: 636587310cec
Revises:
Create Date: 2026-09-10 08:30:34.573058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636587310cec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('town', sa.Text(), nullable=True),
    sa.Column('state_or_province', sa.Text(), nullable=True),
    sa.Column('postcode', sa.Text(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_addresses_town', 'addresses', ['town'], unique=False, mysql_length=100)
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_types',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('is_operational', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('usage_type_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('number_of_points', sa.Integer(), nullable=True),
    sa.Column('status_type_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_status_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['status_type_id'], ['status_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('connection_type_id', sa.Integer(), nullable=True),
    sa.Column('current_type_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('power_kw', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('amps', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['status_type_id'], ['status_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_station_id'), 'connections', ['station_id'], unique=False)
    op.create_table('status_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('status_type_id', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['status_type_id'], ['status_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_station_checked', 'status_snapshots', ['station_id', 'checked_at'], unique=False)
    op.create_table('connection_status_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('status_type_id', sa.Integer(), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('town', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['status_type_id'], ['status_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'connection_id', name='uq_connection_status_daily_date_connection')
    )
    op.create_index('idx_csd_connection_date', 'connection_status_daily', ['connection_id', 'snapshot_date'], unique=False)
    op.create_index('idx_csd_date_working', 'connection_status_daily', ['snapshot_date', 'is_working'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_csd_date_working', table_name='connection_status_daily')
    op.drop_index('idx_csd_connection_date', table_name='connection_status_daily')
    op.drop_table('connection_status_daily')
    op.drop_index('idx_snapshots_station_checked', table_name='status_snapshots')
    op.drop_table('status_snapshots')
    op.drop_index(op.f('ix_connections_station_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('stations')
    op.drop_table('status_types')
    op.drop_table('operators')
    op.drop_index('idx_addresses_town', table_name='addresses', mysql_length=100)
    op.drop_table('addresses')
    # ### end Alembic commands ###
